### ISSUE TITLE
Thread safety issue

### ISSUE THREAD

**Issue by xiaopengli89** [n4r1b/ferrisetw#26] opened 2022-09-07 06:30 UTC
ferrisetw has a thread safety issue(xiaopengli89/precord#9), I checked the code and the cause of the issue should be here:

https://github.com/n4r1b/ferrisetw/blob/master/src/trace.rs#L99

**Comment by daladim** [comment] 2022-09-09 10:14
There definitely could be some thread-safety issues, I'll have a look at it.

Do you have more context? Did you run into bugs/crashes? Is there any debugging log you'd like to share? What makes you think that line is the cause of your issue?

Thanks

**Comment by xiaopengli89** [comment] 2022-09-09 11:21
Multiple threads modify schemas at the same time(https://github.com/n4r1b/ferrisetw/blob/master/src/schema.rs#L130), resulting in crashes or memory errors.

**Comment by daladim** [comment] 2022-09-19 09:07
I'm planning to take care of this in an upcoming release of this crate

**Comment by daladim** [comment] 2022-10-07 13:54
Hello. If you're on a hurry, you can have try to use [this temporary branch](https://github.com/daladim/ferrisetw/commits/experiments_oct_4), which resolves the very issue you've pinpointed.
That's a draft of version 1.0, which has breaking changes from the released 0.1.1

There is some extra work to do however regarding possible race conditions between threads where one thread would drop the `UserTrace` while another is still running a callback. I'll fix this in an upcoming PR as well.

**Comment by daladim** [comment] 2023-01-13 16:49
This has been fixed in ferrisetw 1.0

**Closed as completed by daladim** 2023-01-13 16:49 UTC
